version: '3'
# volumes:
#   dados:
# networks:
#   banco:
#   web:
#   fila:
services:
  # db:
  #   image: postgres:9.6
  #   volumes:
  #     # Volume dos dados
  #     - dados:/var/lib/postgresql/data
  #     # Scripts
  #     - ./scripts:/scripts
  #     - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - banco
  
  # db:
  #   image: mysql:5.7
  #   volumes:
  #   - /var/lib/mysql
  #   environment:
  #   - MYSQL_ROOT_PASSWORD=phprs
  #   - MYSQL_DATABASE=phprs
  web:
    # image: nginx:1.13
    build: ./web
    container_name: apache_web
    restart: always
    #command: bash ./apache.sh
    volumes:
      # Site
      - C:\home\sistemas:/var/www/html
      # Configuração do proxy reverso
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./web/default.conf:/etc/apache2/sites-enabled/default.conf
      # - C:\home\sistemas:/etc/apache2/html/www
    ports:
      - 8081:80
    # networks:
    #   - web
    # depends_on:
    #   - app
  # app:
  #   image: python:3.6
  #   volumes:
  #     # Aplicação
  #     - ./app:/app
  #   working_dir: /app
  #   command: bash ./app.sh
  #   networks:
  #     - banco
  #     - web
  #     - fila
  #   depends_on:
  #     - db
  #     - queue
  #   environment:
  #     - DB_NAME=abc_sender
  # queue:
  #   image: redis:3.2
  #   networks:
  #     - fila
  # worker:
  #   build: worker
  #   volumes:
  #     # Worker
  #     - ./worker:/worker
  #   working_dir: /worker
  #   command: worker.py
  #   networks:
  #     - fila
  #   depends_on:
  #     - queue